version: "3"
services:
  angular-ui:
    build: .
    ports:
      - "4200:4200"
      - "49153:49153"
      - "9876:9876"
      - "49152:49152"
    volumes:
      - ./:/usr/src/app
    command: npm start
